### ISSUE TITLE
Parse error with -haddock

### ISSUE THREAD

**Issue by sjakobi** [haskell/hsc2hs#11]
```
CrossCodegen.hs:394:48:
    parse error on input ‘-- |u' - l'| < |u - l|’
```

**Comment by sjakobi** [comment]
Thanks for the prompt fix, @hvr! :)

**Comment by cartazio** [comment]
(its impossible to cabal v2-install cabal-install atm because of this issue)

**Comment by hvr** [comment]
@cartazio I'm afraid that `hsc2hs` isn't currently in a releasable state currently... there's still some in-flight changes waiting to get merged for ghc 8.8

**Comment by RyanGlScott** [comment]
FWIW, I'd be fine with making a point release without the recent commits related to parsing (which haven't been well tested yet).

**Comment by hvr** [comment]
@RyanGlScott that's an option we could go for if this is considered an urgent enough issue
