### ISSUE TITLE
GHC does not build with hsc2hs master

### ISSUE THREAD

**Issue by andrewthad** [haskell/hsc2hs#16]
I'm not sure if this is a result of the changes to [support data constructor promotion](https://github.com/haskell/hsc2hs/pull/13), but GHC fails to build with hsc2hs master branch. The problem happens when building `directory`. The file [`System/Directory/Internal/Windows.hsc`](https://github.com/haskell/directory/blob/19d6dc0d33366a8920bf8acc7a0fd3ef533d39c3/System/Directory/Internal/Windows.hsc), which I've permalinked to the commit that GHC is currently using, begins with:

```
{-# LANGUAGE CPP #-}
module System.Directory.Internal.Windows where
#include <HsDirectoryConfig.h>
#if defined(mingw32_HOST_OS)
##if defined(i386_HOST_ARCH)
## define WINAPI stdcall
##elif defined(x86_64_HOST_ARCH)
## define WINAPI ccall
##else
## error unknown architecture
##endif
#include <shlobj.h>
#include <windows.h>
#include <System/Directory/Internal/utility.h>
#include <System/Directory/Internal/windows_ext.h>
import Prelude ()
```

When building this on my linux box (presumably this failed on windows hosts as well), the error I get is:

```
Windows.hsc:132:0: error: unterminated #if
Windows.hsc:69:0: error: unterminated #if
Windows.hsc:4:0: error: unterminated #if
```

I don't totally understand the interaction between `hsc2hs` and the CPP extension that's going on here.

**Comment by RyanGlScott** [comment]
[These](https://github.com/haskell/hsc2hs/compare/a816333...ff3ed88dae4da213485cd035ee8aac036b83f09c) are the only commits between GHC's current `hsc2hs` commit and HEAD, so it does seem likely that ff3ed88dae4da213485cd035ee8aac036b83f09c is the culprit. (Do let me know if I should revert it in the meantime.)
