### ISSUE TITLE
do a release that fixes -haddock ghc flag

### ISSUE THREAD

**Issue by cartazio** [haskell/hsc2hs#21]
CrossCodegen.hs:406:48: error:
    parse error on input ‘-- |u' - l'| < |u - l|’
    |
406 |             u'-l' < u-l)                       -- |u' - l'| < |u - l|
    |                                                ^^^^^^^^^^^^^^^^^^^^^^
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/ProjectOrchestration.hs:977:55 in main:Distribution.Client.ProjectOrchestration
cabal: Failed to build code-page-0.2 because it depends on code-page-0.2 which
itself failed to build.
Failed to build hsc2hs-0.68.4-964211cf.

**Comment by cartazio** [comment]
cc @hv

**Comment by cartazio** [comment]
@hvr

**Comment by RyanGlScott** [comment]
This was fixed in [`hsc2hs-0.68.6`](http://hackage.haskell.org/package/hsc2hs-0.68.6), which is now on Hackage.
