### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by googleson78** [haskell/hsc2hs#24]
The [link in the description](http://downloads.haskell.org/~ghc/master/users-guide/utils.html#writing-haskell-interfaces-to-c-code-hsc2hs) appears to be broken.

**Comment by RyanGlScott** [comment]
This appears to be an issue with http://downloads.haskell.org/~ghc/master in general.

**Comment by gbaz** [comment]
The gitlab manual is back up, but the link still needs to be repointed since the redirects aren't entirely precise. It should be updated to https://ghc.gitlab.haskell.org/ghc/doc/users_guide/utils.html#writing-haskell-interfaces-to-c-code-hsc2hs

**Comment by gbaz** [comment]
or hm, maybe i could fix the redirects. standby.

**Comment by gbaz** [comment]
ok, redirects fixed though it will probably take the caches sometime to clear.
