### ISSUE TITLE
Compilation issues with GHC 8.8 due to the MonadFail change-over.

### ISSUE THREAD

**Issue by ekmett** [haskell/hsc2hs#27]
```
HSCParser.hs:41:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
   |
41 |     fail msg = Parser $ \pos _ -> Failure pos msg
   |     ^^^^
```

**Comment by phadej** [comment]
I made revisions for three latest releases: https://hackage.haskell.org/package/hsc2hs-0.68.4/revisions/

There are no hsc2hc compatible with ghc-8.8 (but there's patch in head.hackage).

**Comment by hvr** [comment]
This has been fixed last year already in Git via 6324184483b20233a67cb9b26c59e751738c57c7  and the upcoming hsc2hs-0.68.6 release (to go along with GHC 8.8.1) will contain it

**Comment by RyanGlScott** [comment]
[`hsc2hs-0.68.6`](http://hackage.haskell.org/package/hsc2hs-0.68.6) is now on Hackage.

**Comment by perlpunk** [comment]
I ran into the same error message for https://github.com/orenbenkiki/yamlreference
Any idea why on alpine linux ghc 8.3.3 is delivered with hsc2hs 0.68.5?
```
/ # hsc2hs --version
hsc2hs version 0.68.5
/ # ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.3
```
```
Configuring executable 'yaml2yeast' for YamlReference-0.10.0..
Preprocessing executable 'yaml2yeast' for YamlReference-0.10.0..
Building executable 'yaml2yeast' for YamlReference-0.10.0..
[1 of 2] Compiling Text.Yaml.Reference ( Text/Yaml/Reference.hs, /tmp/yamlreference-master/dist-newstyle/build/x86_64-linux/ghc-8.8.3/YamlReference-0.10.0/x/yaml2yeast/build/yaml2yeast/yaml2yeast-tmp/Text/Yaml/Reference.o )                        

Text/Yaml/Reference.hs:711:3: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
711 |   fail message = Parser $ \ state -> failReply state message
    |   ^^^^
```
Should I build hsc2hs from source or maybe wait for an alpine update?
