### ISSUE TITLE
command-line flag overriding semantics is wrong

### ISSUE THREAD

**Issue by simonmar** [haskell/hsc2hs#35]
hsc2hs parses options using `getOpt` with this code:

```
    let (fs, files, errs) = getOpt Permute options args
    let mode = foldl (.) id fs emptyMode
```

the list of functions returned by `getOpt` is combined with `foldl (.)` which means that earlier options override later ones, not the other way around.

In order to use hsc2hs with C++ (#26) I need to work around this behaviour in Cabal. It's not clear that we should fix it in hsc2hs, because fixing it would break the workaround in Cabal and we would need annoying/fragile version-dependent logic. So I'm just recording the issue in this ticket for posterity.

**Comment by phadej** [comment]
It can be fixed in `hsc2hs` and then you can require `build-tool-depends: hsc2hs:hsc2hs >= fixed-version`
