### ISSUE TITLE
Release for GHC 8.10.1

### ISSUE THREAD

**Issue by bgamari** [haskell/hsc2hs#41]
GHC 8.10.1 will ship with `hsc2hs` based upon 0b44990. It would be great to have a release cut based upon this commit sometime in the next week.

**Comment by bgamari** [comment]
@hvr, what can we do to move this along?

**Comment by arrowd** [comment]
/me doubles the request. Can we have a new Hackage release supporting new GHC? I'm mainly interested in 8.8.3.

**Comment by arrowd** [comment]
Ah, disregard my comment, hsc2hs 0.68.6 seems to work with GHC 8.8.

**Comment by bgamari** [comment]
@hvr, we do need to move this and `unix` forward. I am setting aside this weekend to cut the final 8.10.1.

**Comment by sjakobi** [comment]
v0.68.7 is on Hackage: http://hackage.haskell.org/package/hsc2hs-0.68.7
