### ISSUE TITLE
A --via-nm flag in addition to --via-asm?

### ISSUE THREAD

**Issue by TerrorJack** [haskell/hsc2hs#59]
When doing cross-compilation, we compute the constants using a slow trial-and-error loop or an assembly file parser which is complex and may fail for certain assembly inputs. GHC's `deriveConstants` program uses a different approach: it uses `nm` to read data segment length info from object files to recover the constants, and parsing `nm` output is much simpler and faster.

Does the idea of adding a `--via-nm` mode in `hsc2hs` sound meaningful? If there's enough interest I may give it a shot myself. cc @angerman

**Comment by angerman** [comment]
I don’t think the slowdown comes from the assembly parsing. It’s pretty close to how we do the native one. The big difference is that for native we put multiple statements into the same file.

The really slow part is without even the assembly parsing.

If you can make it work with —via-nm I wouldn’t be opposed to that at all.

**Comment by TerrorJack** [comment]
Closing this since `llvm-nm` is very broken for `wasm32`.
