### ISSUE TITLE
Release for ghc 9.2.1 compat

### ISSUE THREAD

**Issue by sullyj3** [haskell/hsc2hs#64]
It looks like #53 did the trick but that one's not on hackage yet.

**Comment by liskin** [comment]
/me run into this today when trying to `cabal install ghcid`, had to `allow-newer: *:base` in `cabal.project`

**Comment by andreasabel** [comment]
I could bump the `base` bound on hackage, but maybe @bgamari has other plans?

**Comment by patrickt** [comment]
Blocked over here too.

**Comment by bgamari** [comment]
I have pushed 0.68.8.
